name: safe_droid
description: Middleware de detection de malware sur la plateform Android.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0-348.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Bordure pointillées
  dotted_border: ^2.0.0+3
  # Service en backgroud
  flutter_background_service: ^3.0.1
  flutter_background_service_android: ^4.0.2
  permission_handler: ^10.4.3
  # Liste application installées
  installed_apps: ^1.3.1
  dio: ^5.2.1+1
  # Gestion Icon
  flutter_svg: ^2.0.7
  # Notification
  awesome_notifications: ^0.7.4+1
  # Ecoute des Intents
  #android_intent_plus: ^3.1.9
  # Link API rest
  http: ^0.13.6
  # Spinner de chargement
  flutter_spinkit: ^5.2.0
  # Selection de fichier
  file_picker: ^5.3.0
  # Floating Button
  #animated_floating_buttons: ^0.0.2
  # Notification Badge
  #flutter_app_badger: ^1.5.0
  #android_intent_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
